# Generated by Django 5.0.14 on 2026-01-14 22:53

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("razao_social", models.CharField(max_length=180)),
                ("nome_fantasia", models.CharField(blank=True, max_length=180)),
                (
                    "cnpj",
                    models.CharField(
                        blank=True,
                        help_text="Somente números (14 dígitos).",
                        max_length=14,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CNPJ deve conter exatamente 14 dígitos (somente números).",
                                regex="^\\d{14}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=180)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("ativa", models.BooleanField(default=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresas",
                "ordering": ["razao_social"],
            },
        ),
    ]
